---
title: "addCItofigs"
author: "Nicole Kleman"
date: "2024-04-01"
output: html_document
---

Fig2 and Fig3 results are average of 10 replicates, we'll add CI band for each of them by bootstrapping 100x. \# dummy dataset

```{r}
toy=dat[dat$P==0 & dat$t==0 & dat$cov=="pos" ,]
library(dplyr)
boot=tibble(num = 1:100) %>% 
  group_by(num) %>% 
  mutate(mean = mean(sample(toy$vg_gcta, 
                            replace = TRUE))) 
boot_mean=mean(boot$mean)
# Bootstrap 95% percentile confidence interval
boot_CI=quantile(boot$mean, c(0.025,0.975))
# report the mean and CI95%
mean_CIs=tibble(
  vg=boot_mean,
  CI95l=boot_CI[1],
  CI95r=boot_CI[2])
```

# function to bootstrap to get upper and lower end of CI

```{r}
# function to bootstrap: return to mean, CI95l, CI95r
meanCI <- function(data){
  library(dplyr)
  # Resample 100 times, and find the mean of each
  boot=tibble(num = 1:100) %>% 
    group_by(num) %>% 
    mutate(mean = mean(sample(data, 
                              replace = TRUE))) 
  boot_mean=mean(boot$mean)
  # Bootstrap 95% percentile confidence interval
  boot_CI=quantile(boot$mean, c(0.025,0.975))
  # report the mean and CI95%
  mean_CIs=tibble(
    mean=boot_mean,
    CI95l=boot_CI[1],
    CI95r=boot_CI[2])  
  return(mean_CIs)  
}

#meanCI(toy$vg_gcta)

# function to get mean and CIs for each rep
getmeanCI <- function(mydata){
  library(dplyr)
  mydata %>% 
   group_by(t, P, cov) %>% 
   summarise_at(vars("vg_GRMvarX_ganc", "vg_GRMvarX_noa", "vg_GRMvarX_gcta", "vg_GRMld_ganc", "vg_GRMld_noa", "vg_GRMvarX_gcta"), meanCI)}


filename="admix_CGF_theta0.5_gen20_cov_grms.txt"
dat=read.table(filename, header=T)
df_CGF=getmeanCI(dat)

filename="admix_HI_theta0.5_gen20_cov_grms.txt"
dat=read.table(filename, header=T)
df_HI=getmeanCI(dat)

# OUTPUT THE FILE
write.table(df_HI, file="admix_HI_HE_vg_cov_grms_CI.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)
write.table(df_CGF, file="admix_CGF_HE_vg_cov_grms_CI.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)
# THESE CONTAIN P=0.3, 0.6 AS WELL

```

#Remove P at 0.3 and 0.6 for HE regression and combine files (main and CI)

```{r}
#load CI files
HI_HE_CI = read.table("admix_HI_HE_vg_CI.txt", header = TRUE)
CGF_HE_CI = read.table("admix_CGF_HE_vg_CI.txt", header = TRUE)

#Remove P at 0.3 and 0.6 for plotting
CGF_HE_CI = CGF_HE_CI[!(CGF_HE_CI$P %in% 0.3),]
CGF_HE_CI = CGF_HE_CI[!(CGF_HE_CI$P %in% 0.6),]

HI_HE_CI = HI_HE_CI[!(HI_HE_CI$P %in% 0.3),]
HI_HE_CI = HI_HE_CI[!(HI_HE_CI$P %in% 0.6),]

#order to add main file
CGF_HE_CI = CGF_HE_CI[order(CGF_HE_CI$cov, CGF_HE_CI$t),]
HI_HE_CI = HI_HE_CI[order(HI_HE_CI$cov, HI_HE_CI$t),]

#add zero main file into CI file
CGF_zero_main = read.table("HEreg_CGF_zero_main.txt", header = T)
HI_zero_main = read.table("HEreg_HI_zero_main.txt", header = T)

#Remove P at 0.3 and 0.6 for plotting
CGF_zero_main = CGF_zero_main[!(CGF_zero_main$P %in% 0.3),]
CGF_zero_main = CGF_zero_main[!(CGF_zero_main$P %in% 0.6),]

HI_zero_main = HI_zero_main[!(HI_zero_main$P %in% 0.3),]
HI_zero_main = HI_zero_main[!(HI_zero_main$P %in% 0.6),]

#reorder to match CI
CGF_zero_main =CGF_zero_main[order(CGF_zero_main$cov, CGF_zero_main$t),]
HI_zero_main = HI_zero_main[order(HI_zero_main$cov, HI_zero_main$t),]

HEreg_CGF_CI = HEreg_CGF_CI[order(HEreg_CGF_CI$cov, HEreg_CGF_CI$t),]
HEreg_HI_CI = HEreg_HI_CI[order(HEreg_HI_CI$cov, HEreg_HI_CI$t),]

#combine pos, neg, and zero covs
CGF_vg_mat = as.data.table(matrix(data = NA, nrow = 84, ncol = 1))
HI_vg_mat = as.data.table(matrix(data = NA, nrow = 84, ncol = 1))

CGF_vg_mat$exp.vg = HEreg_CGF_CI$exp.vg
CGF_vg_mat$va.term1 = HEreg_CGF_CI$va.term1
CGF_vg_mat$va.term2 = HEreg_CGF_CI$va.term2
CGF_vg_mat$va.term3 = HEreg_CGF_CI$va.term3
CGF_vg_mat$va.term4 = HEreg_CGF_CI$va.term4

HI_vg_mat$exp.vg = HEreg_HI_CI$exp.vg
HI_vg_mat$va.term1 = HEreg_HI_CI$va.term1
HI_vg_mat$va.term2 = HEreg_HI_CI$va.term2
HI_vg_mat$va.term3 = HEreg_HI_CI$va.term3
HI_vg_mat$va.term4 = HEreg_HI_CI$va.term4

CGF_vg_mat = subset(CGF_vg_mat, select = -c(V1))
HI_vg_mat = subset(HI_vg_mat, select = -c(V1))

#for zeros main vg
CGF_vg_mat_zero = as.data.table(matrix(data = NA, nrow = 42, ncol = 1))
HI_vg_mat_zero = as.data.table(matrix(data = NA, nrow = 42, ncol = 1))

CGF_vg_mat_zero$exp.vg = CGF_zero_main$vg.sum
CGF_vg_mat_zero$va.term1 = CGF_zero_main$vg.term1
CGF_vg_mat_zero$va.term2 = CGF_zero_main$vg.term2
CGF_vg_mat_zero$va.term3 = CGF_zero_main$vg.term3
CGF_vg_mat_zero$va.term4 = CGF_zero_main$vg.term4

HI_vg_mat_zero$exp.vg = HI_zero_main$vg.sum
HI_vg_mat_zero$va.term1 = HI_zero_main$vg.term1
HI_vg_mat_zero$va.term2 = HI_zero_main$vg.term2
HI_vg_mat_zero$va.term3 = HI_zero_main$vg.term3
HI_vg_mat_zero$va.term4 = HI_zero_main$vg.term4

CGF_vg_mat_zero = subset(CGF_vg_mat_zero, select = -c(V1))
HI_vg_mat_zero = subset(HI_vg_mat_zero, select = -c(V1))

CGF_vg = rbind(CGF_vg_mat, CGF_vg_mat_zero)
HI_vg = rbind(HI_vg_mat, HI_vg_mat_zero)

#add vg to CI files
CGF_HE_CI$exp.vg = CGF_vg$exp.vg
CGF_HE_CI$va.term1 = CGF_vg$va.term1
CGF_HE_CI$va.term2 = CGF_vg$va.term2
CGF_HE_CI$va.term3 = CGF_vg$va.term3
CGF_HE_CI$va.term4 = CGF_vg$va.term4

HI_HE_CI$exp.vg = HI_vg$exp.vg
HI_HE_CI$va.term1 = HI_vg$va.term1
HI_HE_CI$va.term2 = HI_vg$va.term2
HI_HE_CI$va.term3 = HI_vg$va.term3
HI_HE_CI$va.term4 = HI_vg$va.term4

#output files
write.table(HI_HE_CI, file="admix_HI_HE_vg_CI_P0_P9_cov.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)
write.table(CGF_HE_CI, file="admix_CGF_HE_vg_CI_P0_P9_cov.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)

#output files without zeros
CGF_HE_CI = CGF_HE_CI[!(CGF_HE_CI$cov %in% "zero"),]

HI_HE_CI = HI_HE_CI[!(HI_HE_CI$cov %in% "zero"),]

write.table(HI_HE_CI, file="admix_HI_HE_vg_CI_P0_P9_posneg.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)
write.table(CGF_HE_CI, file="admix_CGF_HE_vg_CI_P0_P9_posneg.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)

#combine CI files with expected values from main file
CGF_CI_cov = read.table("admix_CGF_HE_vg_CI_P0_P9_cov.txt", header = T)
HI_CI_cov = read.table("admix_HI_HE_vg_CI_P0_P9_cov.txt", header = T)


#combine CI files with expected values from main file
CGF_CI_pn = read.table("admix_CGF_HE_vg_CI_P0_P9_posneg.txt", header = T)
HI_CI_pn = read.table("admix_HI_HE_vg_CI_P0_P9_posneg.txt", header = T)

HEreg_CGF_CI = read.table("HEreg_CGF.txt", header = T)
HEreg_HI_CI = read.table("HEreg_HI.txt", header = T)

#Remove P at 0.3 and 0.6 for plotting
HEreg_CGF_CI = HEreg_CGF_CI[!(HEreg_CGF_CI$P %in% 0.3),]
HEreg_CGF_CI = HEreg_CGF_CI[!(HEreg_CGF_CI$P %in% 0.6),]

HEreg_HI_CI = HEreg_HI_CI[!(HEreg_HI_CI$P %in% 0.3),]
HEreg_HI_CI = HEreg_HI_CI[!(HEreg_HI_CI$P %in% 0.6),]

CGF_CI_pn$exp.vg = HEreg_CGF_CI$exp.vg
CGF_CI_pn$va.term1 = HEreg_CGF_CI$va.term1
CGF_CI_pn$va.term2 = HEreg_CGF_CI$va.term2
CGF_CI_pn$va.term3 = HEreg_CGF_CI$va.term3
CGF_CI_pn$va.term4 = HEreg_CGF_CI$va.term4

HI_CI_pn$exp.vg = HEreg_HI_CI$exp.vg
HI_CI_pn$va.term1 = HEreg_HI_CI$va.term1
HI_CI_pn$va.term2 = HEreg_HI_CI$va.term2
HI_CI_pn$va.term3 = HEreg_HI_CI$va.term3
HI_CI_pn$va.term4 = HEreg_HI_CI$va.term4

write.table(HI_CI_pn, file="admix_HI_HE_vg_CI_P0_P9_posneg.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)
write.table(CGF_CI_pn, file="admix_CGF_HE_vg_CI_P0_P9_posneg.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)

```

# Combine Scaled GRMs with CI_posneg file

```{r}
#load CI_posneg file
CGF_CI_pn = read.table("admix_CGF_HE_vg_CI_P0_P9_posneg.txt", header = T)
HI_CI_pn = read.table("admix_HI_HE_vg_CI_P0_P9_posneg.txt", header = T)

#load Scaled GRMs CI
CGF_grms = read.table("admix_CGF_HE_vg_grms_CI.txt", header = T)
HI_grms = read.table("admix_HI_HE_vg_grms_CI.txt", header = T)

#remove P=0.3, 0.6 for scaled grms
CGF_grms = CGF_grms[!(CGF_grms$P %in% 0.3),]
CGF_grms = CGF_grms[!(CGF_grms$P %in% 0.6),]

HI_grms = HI_grms[!(HI_grms$P %in% 0.3),]
HI_grms = HI_grms[!(HI_grms$P %in% 0.6),]

#combine files
CGF_CI_grms = merge(CGF_CI_pn, CGF_grms, by=c("t", "P", "cov"))
HI_CI_grms = merge(HI_CI_pn, HI_grms, by=c("t", "P", "cov"))

#output main figure 4 file
write.table(CGF_CI_grms, file="admix_CGF_HE_vg_CI_P0_P9_posneg_grms.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)
write.table(HI_CI_grms, file="admix_HI_HE_vg_CI_P0_P9_posneg_grms.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)

```

# Combine Scaled GRMs with CI_cov file
```{r}
#load CI_posneg file
CGF_CI_cov = read.table("admix_CGF_HE_vg_CI_P0_P9_cov.txt", header = T)
HI_CI_cov = read.table("admix_HI_HE_vg_CI_P0_P9_cov.txt", header = T)

#load Scaled GRMs CI
CGF_grms = read.table("admix_CGF_HE_vg_cov_grms_CI.txt", header = T)
HI_grms = read.table("admix_HI_HE_vg_cov_grms_CI.txt", header = T)

#remove P=0.3, 0.6 for scaled grms
CGF_grms = CGF_grms[!(CGF_grms$P %in% 0.3),]
CGF_grms = CGF_grms[!(CGF_grms$P %in% 0.6),]

HI_grms = HI_grms[!(HI_grms$P %in% 0.3),]
HI_grms = HI_grms[!(HI_grms$P %in% 0.6),]

#combine files
CGF_CI_grms = merge(CGF_CI_cov, CGF_grms, by=c("t", "P", "cov"))
HI_CI_grms = merge(HI_CI_cov, HI_grms, by=c("t", "P", "cov"))

#output main figure 4 file
write.table(CGF_CI_grms, file="admix_CGF_HE_vg_CI_P0_P9_cov_grms.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)
write.table(HI_CI_grms, file="admix_HI_HE_vg_CI_P0_P9_cov_grms.txt",
            quote = FALSE, sep = "\t",
            row.names = FALSE, col.names = TRUE)
```

